services:
  srt-splitter:
    build: .
    container_name: srt-splitter
    ports:
      - "9000:9000/udp"
    environment:
      - YOUTUBE_KEY_LEFT=${YOUTUBE_KEY_LEFT}
      - YOUTUBE_KEY_RIGHT=${YOUTUBE_KEY_RIGHT}
      - SRT_INPUT_PASSPHRASE=${SRT_INPUT_PASSPHRASE}
    restart: unless-stopped
