worker_processes auto;
events { worker_connections 1024; }

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;

            exec_push ffmpeg -i rtmp://127.0.0.1:1935/live/$name
                -filter_complex "[0:a]pan=stereo|c0=c0|c1=c0[a_en];[0:a]pan=stereo|c0=c1|c1=c1[a_de]"
                -map 0:v -map "[a_en]" -c:v copy -c:a aac -b:a 160k
                    -f flv "rtmp://a.rtmp.youtube.com/live2/${YT_KEY_EN}"
                -map 0:v -map "[a_de]" -c:v copy -c:a aac -b:a 160k
                    -f flv "rtmp://a.rtmp.youtube.com/live2/${YT_KEY_DE}";
        }
    }
}

